trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: myapp
  tag: $(Build.BuildId)
  acrName: dockeracrpush   # your ACR name

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuildPush
    displayName: Docker Build and Push
    steps:

    # Checkout repo
    - checkout: self

    # Log in to Azure (ARM service connection)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'docker-build-acr'   # Azure RM service connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    # Build Docker image
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-svc'
        repository: 'myapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        addPipelineData: false
        addBaseImageData: false

    # Push Docker image
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-svc'
        repository: 'myapp'
        command: 'push'
